apiVersion: v1
kind: Service
metadata:
  name: sqtest4
spec:
  selector:
    app: sqtest4
  ports:
  - name: web
    nodePort: 30084
    port: 80
    protocol: TCP
    targetPort: 80
  type: NodePort
