apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sqtest4-app
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: sqtest4
  project: sqtest4-project
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: deploy/resources
    repoURL: https://github.com/tanuudemo/sqtest4.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - Replace=true
